# Generated by Django 5.0.2 on 2024-05-13 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
    ]
