# Generated by Django 5.0.2 on 2024-05-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='users.CustomUser',
        ),
    ]
