version: "3.9"

services:
  server:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 8001:8001
    depends_on:
      - db


  db:
    image: postgis/postgis:15-3.4-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432


volumes:
  pgdata: